import Content from "@/components/Content";
import Partner from "@/components/Partner";
import Head from "next/head";
import Banner from "@/components/Banner";

import {
  bannerTitle,
  bannerSubTitleOne,
  bannerSubTitleTwo,
  bannerSubTitleThree,
  bannerExploreBtn,
  bannerCreateBtn,
} from "../const";

export default function Home() {
  return (
    <div className="bg-fixed bg-center bg-cover bannerBg bg-opacity-10">
      <Head>
        <title>Gammer...</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner
        Title={bannerTitle}
        subTitleOne={bannerSubTitleOne}
        subTitleTwo={bannerSubTitleTwo}
        subTitleThree={bannerSubTitleThree}
        explore={bannerExploreBtn}
        create={bannerCreateBtn}
      />
      <Content/>
      <Partner/>
    </div>
  );
}
